# Generated by Django 5.2.3 on 2025-06-30 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default='00000', help_text='Enter a 5-digit or 5+4 digit zip code.', max_length=10, validators=[django.core.validators.RegexValidator(message='Enter a valid zip code (e.g., 12345 or 12345-6789).', regex='^\\d{5}(?:[-\\s]\\d{4})?$')]),
        ),
    ]
