# Generated by Django 5.1.6 on 2025-06-30 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_address_zip_code'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')        
        """, """
            DELETE FROM store_collection
            WHERE title='collection1'
        """)
    ]
