# Generated by Django 5.1.6 on 2025-07-03 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20250701_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='birth_dae',
            new_name='birth_date',
        ),
    ]
